spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell


#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.sblueice.controller: com.imooc.sell.LoggerTest:debug
wechat:
  myAppId: wx293b159deb132d81
  myAppSecret: cf34be81b3e808f12e5967c1189d23b9
  mchId:
  mchKey:
  keyPath:
  notifyUrl:http://sellol.nat300.top/sell/pay/notify